sudo: required
language: generic 

services:
  - docker


before_install:
  - docker build -t dvrushank/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dvrushank/docker-react npm run test
